services:
    vse.topicimagepreview.factory:
        class: vse\topicimagepreview\factory
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@user'

    vse.topicimagepreview.preview:
        class: vse\topicimagepreview\event\preview
        arguments:
            - '@config'
            - '@vse.topicimagepreview.factory'
        tags:
            - { name: event.listener }

    vse.topicimagepreview.settings:
        class: vse\topicimagepreview\event\settings
        arguments:
            - '@config'
            - '@language'
            - '@request'
            - '@template'
            - '@user'
        tags:
            - { name: event.listener }
